version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes: 
      - ./backend:/app  # Poprawne mapowanie wolumenu
    environment:
      FLASK_ENV: development
      DATABASE_URL: postgresql://postgres:password@db:5432/mydatabase  # Usuń "-" przed zmienną
    depends_on:
      - db
    networks:
      - theater_network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    networks:
      - theater_network

networks:
  theater_network:  # Definiowanie wspólnej sieci dla obu kontenerów
    driver: bridge
